# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea0f67159e9c365003863da57331980ce358fcd892571269c458fedede3fded6267ed37090bd54da7cc887de575a7cb09ad5969c10c5ba939e974b9e27cd9339

test:
  secret_key_base: fe6926173e7da41cee6df6315888294ec5549871b9fba50cf8ed31feea77b05c710fa4a95eff020f4c8b357a12b4bb4c2a5050ff2bb8fb5ac60dd1c25840232a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
